In [61]:

import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import os

In [62]:
movie = pd.read_csv(r"D:\project\Movie Analysis (1)\Movie Analysis\tmdb_5000_movies.csv\tmdb_5000_movies.csv")
credits = pd.read_csv(r"D:\project\Movie Analysis (1)\Movie Analysis\tmdb_5000_credits.csv\tmdb_5000_credits.csv")

In [63]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [64]:
movie.shape

(4803, 20)

In [65]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [66]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [67]:
film = movie.merge(credits, on='title')

In [68]:
film.shape

(4809, 23)

In [69]:
film.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [70]:
major = film[['movie_id', 'title', 'overview','genres','keywords','cast','crew','release_date','vote_average']]

In [71]:
major.shape

(4809, 9)

In [72]:
major.isnull().sum()

movie_id        0
title           0
overview        3
genres          0
keywords        0
cast            0
crew            0
release_date    1
vote_average    0
dtype: int64

In [73]:
major.dropna(inplace=True)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\1198995870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major.dropna(inplace=True)

In [74]:
major.isnull().sum()

movie_id        0
title           0
overview        0
genres          0
keywords        0
cast            0
crew            0
release_date    0
vote_average    0
dtype: int64

In [75]:
major.shape

(4805, 9)

In [76]:
major.duplicated().sum()

np.int64(0)

In [77]:
major.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19,6.9

In [78]:
major.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [79]:
major['release_date'] = pd.to_datetime(major['release_date'] )

major['year'] = major['release_date'].dt.year

available_years = major['year'].dropna().unique()
available_years.sort()

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3989670504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['release_date'] = pd.to_datetime(major['release_date'] )
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3989670504.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['year'] = major['release_date'].dt.year

In [80]:
import ast 

def convert_genres(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])

    return l

In [81]:
major['genres'] = major['genres'].apply(convert_genres)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\1044868011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['genres'] = major['genres'].apply(convert_genres)

In [82]:
major.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19,6.9,2007

In [83]:
import ast 

def convert_keywords(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])

    return l

major['keywords'] = major['keywords'].apply(convert_keywords)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2091915770.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['keywords'] = major['keywords'].apply(convert_keywords)

In [84]:
major.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19,6.9,2007

In [85]:
def convert_cast(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            l.append(i['name'])
        counter +=1
    return l

In [86]:
major['cast'] = major['cast'].apply(convert_cast)
major.head(2)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2365179223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['cast'] = major['cast'].apply(convert_cast)

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19,6.9,2007

In [87]:
def convert_crew(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            l.append(i['name'])
        counter +=1
    return l

major['crew'] = major['crew'].apply(convert_crew)
major.head(2)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3975085628.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['crew'] = major['crew'].apply(convert_crew)

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",2007-05-19,6.9,2007

In [88]:
major['overview'] = major['overview'].apply(lambda x:x.split())
major.head()

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3095422983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['overview'] = major['overview'].apply(lambda x:x.split())

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",2007-05-19,6.9,2007
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock]",2015-10-26,6.3,2015
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan]",2012-07-16,7.6,2012
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter]",2012-03-07,6.1,2012

In [89]:
def remove_space(word):
    l =[]
    for i in word:
        l.append(i.replace(" ",""))
    return l

In [90]:
major.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[Stephen E. Rivkin, Rick Carter, Christopher B...",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",2007-05-19,6.9,2007
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[Thomas Newman, Sam Mendes, Anna Pinnock]",2015-10-26,6.3,2015
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[Hans Zimmer, Charles Roven, Christopher Nolan]",2012-07-16,7.6,2012
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[Andrew Stanton, Andrew Stanton, John Lasseter]",2012-03-07,6.1,2012

In [91]:
major['cast'] = major['cast'].apply(remove_space)
major['crew'] = major['crew'].apply(remove_space)
major['genres'] = major['genres'].apply(remove_space)
major['keywords'] = major['keywords'].apply(remove_space)
major['overview'] = major['overview'].apply(remove_space)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3031017514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['cast'] = major['cast'].apply(remove_space)
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3031017514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['crew'] = major['crew'].apply(remove_space)
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3031017514.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['genres'] = major['genres'].apply(remove_space)
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3031017514.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['keywords'] = major['keywords'].apply(remove_space)
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3031017514.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['overview'] = major['overview'].apply(remove_space)

In [92]:
major.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes]",2009-12-10,7.2,2009
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheimer]",2007-05-19,6.9,2007
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock]",2015-10-26,6.3,2015
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan]",2012-07-16,7.6,2012
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter]",2012-03-07,6.1,2012

In [93]:
major['tags'] = major['overview'] + major['genres'] + major['keywords'] + major['cast'] + major['crew']

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2220019762.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  major['tags'] = major['overview'] + major['genres'] + major['keywords'] + major['cast'] + major['crew']

In [94]:
major.head()

,movie_id,title,overview,genres,keywords,cast,crew,release_date,vote_average,year,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes]",2009-12-10,7.2,2009,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheimer]",2007-05-19,6.9,2007,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock]",2015-10-26,6.3,2015,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan]",2012-07-16,7.6,2012,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter]",2012-03-07,6.1,2012,"[John, Carter, is, a, war-weary,, former, mili..."

In [95]:
new_df = major[['movie_id', 'title', 'tags', 'keywords', 'cast', 'crew','genres', 'year','vote_average' ]]

In [96]:
new_df.head()

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes]","[Action, Adventure, Fantasy, ScienceFiction]",2009,7.2
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheimer]","[Adventure, Fantasy, Action]",2007,6.9
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock]","[Action, Adventure, Crime]",2015,6.3
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan]","[Action, Crime, Drama, Thriller]",2012,7.6
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter]","[Action, Adventure, ScienceFiction]",2012,6.1

In [97]:
new_df.iloc[0]['genres']

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [98]:
new_df.head()

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[StephenE.Rivkin, RickCarter, ChristopherBoyes]","[Action, Adventure, Fantasy, ScienceFiction]",2009,7.2
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[DariuszWolski, GoreVerbinski, JerryBruckheimer]","[Adventure, Fantasy, Action]",2007,6.9
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]","[ThomasNewman, SamMendes, AnnaPinnock]","[Action, Adventure, Crime]",2015,6.3
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[HansZimmer, CharlesRoven, ChristopherNolan]","[Action, Crime, Drama, Thriller]",2012,7.6
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[AndrewStanton, AndrewStanton, JohnLasseter]","[Action, Adventure, ScienceFiction]",2012,6.1

In [99]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df['keywords'] = new_df['keywords'].apply(lambda x: " ".join(x))
new_df['cast'] = new_df['cast'].apply(lambda x: " ".join(x))
new_df['crew'] = new_df['crew'].apply(lambda x: " ".join(x))
new_df['genres'] = new_df['genres'].apply(lambda x: " ".join(x))
new_df.head()

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2421994811.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2421994811.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['keywords'] = new_df['keywords'].apply(lambda x: " ".join(x))
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2421994811.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cast'] = new_df['cast'].apply(lambda x: " ".join(x))
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2421994811.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['crew'] = new_df['crew'].apply(lambda x: " ".join(x))
C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\2421994811.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['genres'] = new_df['genres'].apply(lambda x: " ".join(x))

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,StephenE.Rivkin RickCarter ChristopherBoyes,Action Adventure Fantasy ScienceFiction,2009,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,DariuszWolski GoreVerbinski JerryBruckheimer,Adventure Fantasy Action,2007,6.9
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,spy basedonnovel secretagent sequel mi6 britis...,DanielCraig ChristophWaltz LÃ©aSeydoux,ThomasNewman SamMendes AnnaPinnock,Action Adventure Crime,2015,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,dccomics crimefighter terrorist secretidentity...,ChristianBale MichaelCaine GaryOldman,HansZimmer CharlesRoven ChristopherNolan,Action Crime Drama Thriller,2012,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...",basedonnovel mars medallion spacetravel prince...,TaylorKitsch LynnCollins SamanthaMorton,AndrewStanton AndrewStanton JohnLasseter,Action Adventure ScienceFiction,2012,6.1

In [100]:
new_df.iloc[0]['tags']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenE.Rivkin RickCarter ChristopherBoyes'

In [101]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [102]:
new_df.sample()

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
4652,20520,The Motel,thirteen-year-old ernest chin lives and works ...,,JeffreyChyau SungKang JadeWu,MichaelKang MichaelKang,Drama Comedy,2005,7.0

In [103]:
import nltk
nltk.download('punkt')

[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

False

In [104]:
import nltk
from nltk.stem import PorterStemmer

In [105]:
ps = PorterStemmer()

In [106]:
def stems(text):
    l = []
    for  i in text.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [107]:
new_df['tags'] = new_df['tags'].apply(stems)

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\3973021881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stems)

In [108]:
new_df.head()

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,StephenE.Rivkin RickCarter ChristopherBoyes,Action Adventure Fantasy ScienceFiction,2009,7.2
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c...",ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,DariuszWolski GoreVerbinski JerryBruckheimer,Adventure Fantasy Action,2007,6.9
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...,spy basedonnovel secretagent sequel mi6 britis...,DanielCraig ChristophWaltz LÃ©aSeydoux,ThomasNewman SamMendes AnnaPinnock,Action Adventure Crime,2015,6.3
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...,dccomics crimefighter terrorist secretidentity...,ChristianBale MichaelCaine GaryOldman,HansZimmer CharlesRoven ChristopherNolan,Action Crime Drama Thriller,2012,7.6
4,49529,John Carter,"john carter is a war-weary, former militari ca...",basedonnovel mars medallion spacetravel prince...,TaylorKitsch LynnCollins SamanthaMorton,AndrewStanton AndrewStanton JohnLasseter,Action Adventure ScienceFiction,2012,6.1

In [109]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words= "english")

In [110]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [111]:
vector.shape

(4805, 5000)

In [112]:
from sklearn.metrics.pairwise import cosine_similarity

In [113]:
similary = cosine_similarity(vector)

In [114]:
similary

array([[1.        , 0.08006408, 0.08238526, ..., 0.04484485, 0.        ,
        0.        ],
       [0.08006408, 1.        , 0.0571662 , ..., 0.023338  , 0.        ,
        0.02541643],
       [0.08238526, 0.0571662 , 1.        , ..., 0.02401461, 0.        ,
        0.        ],
       ...,
       [0.04484485, 0.023338  , 0.02401461, ..., 1.        , 0.04222003,
        0.04270814],
       [0.        , 0.        , 0.        , ..., 0.04222003, 1.        ,
        0.0919601 ],
       [0.        , 0.02541643, 0.        , ..., 0.04270814, 0.0919601 ,
        1.        ]], shape=(4805, 4805))

In [115]:
vector.shape

(4805, 5000)

In [116]:
new_df[new_df['title'] =='Spider-Man'].index[0]

np.int64(159)

In [117]:
def recommend(movie): 
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similary[index])), reverse=True, key=lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.loc[i[0]].title)

In [118]:
movie.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [119]:
new_df.head(2)

,movie_id,title,tags,keywords,cast,crew,genres,year,vote_average
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...",cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,StephenE.Rivkin RickCarter ChristopherBoyes,Action Adventure Fantasy ScienceFiction,2009,7.2
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c...",ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,DariuszWolski GoreVerbinski JerryBruckheimer,Adventure Fantasy Action,2007,6.9

In [120]:
print("Available Years: ", ",".join(map(str, available_years)))
selected_year = int(input("Select a year from the list above: "))

movies_by_year = new_df[new_df['year'] == selected_year]

print("\nTop 5 Movies from the Year", selected_year)
top_5_movies_year = movies_by_year[['title', 'vote_average']].sort_values(by='vote_average', ascending=False).head(5)
print(top_5_movies_year)

available_genres = new_df['genres'].unique()
print("Available Genres: ", available_genres)

selected_genre = input("\nEnter the genre of the movie: ")
movies_by_genre = new_df[new_df['genres'].str.lower().str.contains(selected_genre.lower(), case=False, na=False)]


print("\nTop Movies in the Genre", selected_genre)
top_5_movies_genre = movies_by_genre[['title', 'vote_average']].sort_values(by='vote_average', ascending=False).head(5)
print(top_5_movies_genre)

movies_choosed = input("\nEnter the movie Name: ")
movies_choosen = new_df[new_df['title'].str.lower().str.contains(movies_choosed.lower(), case=False, na=False)]
print(movies_choosen)

new_df['combined_features'] = new_df['title'] + " " + new_df['tags'] + " " + new_df['cast'] + " " + new_df['year'].astype(str) + " " + new_df['genres']

cv = CountVectorizer()
count_matrix = cv.fit_transform(new_df['combined_features'])

similarity = cosine_similarity(count_matrix)

def recommend(movie_name):
    if movie_name in new_df['title'].values:
        index = new_df[new_df['title'] == movie_name].index[0]

        selected_movie_year = new_df.loc[index,str('year')]

        distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])

        print(f"\nMovies similar to '{movie_name}' from the year {selected_movie_year}:")

        count = 0
        for i in distances[1:]: 
            movie_index = i[0]
            movie_year = new_df.loc[movie_index,str('year')]

            if movie_year == selected_movie_year:
                print(new_df.loc[movie_index, 'title'])
                count += 1
            if count ==6:
                break
    else:
        print(f"Movie '{movie_name}' is not found on our dataset.")

Available Years:  1916,1925,1927,1929,1930,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017

Top 5 Movies from the Year 1980
                        title  vote_average
1992  The Empire Strikes Back           8.2
2286              The Shining           8.1
3573         The Elephant Man           7.9
2346              Raging Bull           7.7
1755       The Blues Brothers           7.5
Available Genres:  ['Action Adventure Fantasy ScienceFiction' 'Adventure Fantasy Action'
 'Action Adventure Crime' ... 'Thriller Horror Comedy' 'Foreign Thriller'
 'Comedy Drama Romance TVMovie']

Top Movies in the Genre action
                        title  vote_average
2388           One Man's Hero           9.3
4541            Seven Samurai           8.2
65            The Dark Knight           8.2
1992  The Empire Strikes Back           8.2
2915                Star Wars           8.1
Empty DataFrame
Columns: [movie_id, title, tags, keywords, cast, crew, genres, year, vote_average]
Index: []

C:\Users\JEEVIKA\AppData\Local\Temp\ipykernel_35940\984734519.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['combined_features'] = new_df['title'] + " " + new_df['tags'] + " " + new_df['cast'] + " " + new_df['year'].astype(str) + " " + new_df['genres']